#!/usr/bin/python3
from subprocess import Popen
import sys

filename = sys.argv[1]
while True:
    #print("\nStarting " + filename)

    print ("""
  _   _      _             _      _    _           _   
 | \ | | ___| |_ ___ _   _| |_   / \  | | ___ _ __| |_  
 |  \| |/ _ \ __/ __| | | | __| / _ \ | |/ _ \ '__| __| 
 | |\  |  __/ || (__| |_| | |_ / ___ \| |  __/ |  | |_  
 |_| \_|\___|\__\___|\__,_|\__/_/   \_\_|\___|_|   \__| FP-022
                                                       
""")

    p = Popen("python3 " + filename, shell=True)
    p.wait()